src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import NotFoundView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls", namespace="students")),
    path("teachers/", include("teachers.urls", namespace="teachers")),
    path("groups/", include("groups.urls", namespace="groups")),
    path("oauth/", include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

src/core/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from core.views import IndexView, Login, Logout, Registration, ActivateUser, ProfileView

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="core"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>", ActivateUser.as_view(), name="activation"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

urlpatterns += staticfiles_urlpatterns()

src/students/urls.py
from django.urls import path

from students.views import StudentView, CreateStudentView, UpdateStudentView, DeleteStudentView, ShowStudentsView

app_name = "students"

urlpatterns = [
    path("", StudentView.as_view(), name="students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
    path("<group>/", ShowStudentsView.as_view(), name="show_students"),
]

src/students/models.py
import random

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from faker import Faker

from groups.models import Group
from core.models import Person


class Student(Person):
    grade = models.PositiveSmallIntegerField(
        null=True,
        validators=[MinValueValidator(1), MaxValueValidator(100)],
    )
    campus = models.BooleanField(
        default=True,
    )
    active = models.BooleanField(
        default=True,
    )
    group = models.ForeignKey(
        to="groups.Group",
        on_delete=models.CASCADE,
    )
    cv = models.FileField(
        default="cv/bartender-cv-template-in-word-and-pdf-format-for.pdf",
        upload_to="cv/",
    )

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()

        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                grade=faker.random.randint(1, 100),
                birth_date=faker.date_time_between(start_date="-30y", end_date="-18y"),
                campus=faker.boolean(),
                active=faker.boolean(),
                group=random.choice(Group.objects.all()),
            )

    class Meta:
        ordering = ("first_name", "last_name")

src/students/forms.py
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

src/students/views.py
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from students.forms import StudentForm
from students.models import Student


class StudentView(LoginRequiredMixin, TemplateView):
    model = Student
    template_name = "students/students.html"

    def get(self, request, *args, **kwargs):
        search_query = request.GET.get("q")
        if search_query:
            students = Student.objects.filter(
                Q(first_name__contains=search_query) | Q(last_name__contains=search_query)
            )
        else:
            students = Student.objects.all()
        self.extra_context = {"students": students}

        return self.render_to_response(self.extra_context)


class CreateStudentView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm
    template_name = "students/students_create.html"
    success_url = reverse_lazy("students:students")


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    template_name = "students/students_update.html"
    success_url = reverse_lazy("students:students")


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy("students:students")
    template_name = "students/students_delete.html"


def show_students(request, group):
    return render(
        request, template_name="students/show_students.html", context={"students": Student.objects.filter(group=group)}
    )


class ShowStudentsView(LoginRequiredMixin, TemplateView):
    model = Student
    template_name = "students/show_students.html"

    def get(self, request, *args, **kwargs):
        students = Student.objects.filter(group=kwargs["group"])
        self.extra_context = {"students": students}

        return self.render_to_response(self.extra_context)

src/templates/students/show_students.html
{% extends "index/index.html" %}
{% load static %}
{% block content %}
    <form action="{% url "students:students" %}" method="get">
        <input class="search" type="text" name="q" placeholder="Search" style="margin-bottom: 3vh">
    </form>
    <a style="width: 100%" type="button" class="btn btn-success" href="{% url "students:create_student" %} ">Create new
        student</a>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Email</th>
            <th scope="col">Course</th>
            <th scope="col">Grade</th>
            <th scope="col">Campus</th>
            <th scope="col">Active</th>
            <th scope="col">CV</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td><img src="{{ student.photo.url }}" height="75vh"></td>
                <td>{{ student.first_name }} {{ student.last_name }}</td>
                <td>{{ student.age }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.group }}</td>
                <td>{{ student.grade }}</td>
                <td>{{ student.campus }}</td>
                <td>{{ student.active }}</td>
                <td><a href="{% static student.cv %}">Download</a></td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url "students:update_student" student.pk %}">Edit</a></td>
                <td><a type="button" class="btn btn-danger"
                       href="{% url "students:delete_student" student.pk %}">Delete</a></td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/students/students.html
{% extends "index/index.html" %}
{% load static %}
{% block content %}
    <form action="{% url "students:students" %}" method="get">
        <input class="search" type="text" name="q" placeholder="Search" style="margin-bottom: 3vh">
    </form>
    <a style="width: 100%" type="button" class="btn btn-success" href="{% url "students:create_student" %} ">Create new
        student</a>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Email</th>
            <th scope="col">Course</th>
            <th scope="col">Grade</th>
            <th scope="col">Campus</th>
            <th scope="col">Active</th>
            <th scope="col">CV</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td><img src="{{ student.photo.url }}" height="75vh"></td>
                <td>{{ student.first_name }} {{ student.last_name }}</td>
                <td>{{ student.age }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.group }}</td>
                <td>{{ student.grade }}</td>
                <td>{{ student.campus }}</td>
                <td>{{ student.active }}</td>
                <td><a href="{{ student.cv.url }}">Download</a></td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url "students:update_student" student.pk %}">Edit</a></td>
                <td><a type="button" class="btn btn-danger"
                       href="{% url "students:delete_student" student.pk %}">Delete</a></td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/students/students_create.html
{% extends "index/index.html" %}

{% block content %}
        <form enctype="multipart/form-data" action="{% url "students:create_student" %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
{% endblock content %}

src/templates/students/students_delete.html
{% extends "index/index.html" %}

{% block content %}
        <form method="post"> {% csrf_token %}
            <h1>Are you sure you want to delete this student?</h1>
            <div>
                <button type="submit" class="btn btn-danger">Submit</button>
            </div>
        </form>
{% endblock content %}

src/templates/students/students_update.html
{% extends "index/index.html" %}

{% block content %}
        <form method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
{% endblock content %}