src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import NotFoundView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls", namespace="students")),
    path("teachers/", include("teachers.urls", namespace="teachers")),
    path("groups/", include("groups.urls", namespace="groups")),
    path("oauth/", include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

src/core/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from core.views import IndexView, Login, Logout, Registration, ActivateUser, ProfileView

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="core"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>", ActivateUser.as_view(), name="activation"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

urlpatterns += staticfiles_urlpatterns()

src/groups/urls.py
from django.urls import path

from groups.views import GroupView, CreateGroupView, UpdateGroupView, DeleteGroupView, ShowGroupView

app_name = "groups"

urlpatterns = [
    path("", GroupView.as_view(), name="groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<uuid:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<uuid:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("<course>/", ShowGroupView.as_view(), name="show_group"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import TeacherView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", TeacherView.as_view(), name="teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:pk>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:pk>", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
import random

from django.db import models
from django.core.validators import MinValueValidator
from faker import Faker

from groups.models import Group
from core.models import Person


class Teacher(Person):
    salary = models.DecimalField(
        default=6500.00,
        validators=[MinValueValidator(6500.00)],
        max_digits=10,
        decimal_places=2,
    )
    group = models.ManyToManyField(to="groups.Group")

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()

        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_time_between(start_date="-80y", end_date="-25y"),
                group=random.choices(Group.objects.all()),
                salary=faker.random.randint(6500, 50000),
            )

    class Meta:
        ordering = ("first_name", "last_name")

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex is not available in our country!")

        return email

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView

from teachers.forms import TeacherForm
from teachers.models import Teacher


class TeacherView(LoginRequiredMixin, TemplateView):
    model = Teacher
    template_name = "teachers/teachers.html"

    def get(self, request, *args, **kwargs):
        search_query = request.GET.get("q")
        if search_query:
            teachers = Teacher.objects.filter(
                Q(first_name__contains=search_query) | Q(last_name__contains=search_query)
            )
        else:
            teachers = Teacher.objects.all()
        self.extra_context = {"teachers": teachers}

        return self.render_to_response(self.extra_context)


class CreateTeacherView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherForm
    template_name = "teachers/teachers_create.html"
    success_url = reverse_lazy("teachers:teachers")


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherForm
    template_name = "teachers/teachers_update.html"
    success_url = reverse_lazy("teachers:teachers")


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy("teachers:teachers")
    template_name = "teachers/teachers_delete.html"

src/templates/teachers/teachers.html
{% extends "index/index.html" %}
{% load static %}
{% block content %}
    <form action="{% url "teachers:teachers" %}" method="get">
        <input class="search" type="text" name="q" placeholder="Search" style="margin-bottom: 3vh">
    </form>
    <a style="width: 100%" type="button" class="btn btn-success" href="{% url "teachers:create_teacher" %}">Create new
        teacher</a>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Email</th>
            <th scope="col">Course</th>
            <th scope="col">Salary</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>

        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <td><img src="{{ teacher.photo.url }}" height="75vh"></td>
                <td>{{ teacher.first_name }} {{ teacher.last_name }}</td>
                <td>{{ teacher.age }}</td>
                <td>{{ teacher.email }}</td>
                <td>{% for group in teacher.group.all %}<a type="button" class="btn btn-secondary" href="{% url "groups:show_group" group %}">{{ group }}</a> {% endfor %}</td>
                <td>{{ teacher.salary }}</td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url "teachers:update_teacher" teacher.pk %}">Edit</a></td>
                <td><a type="button" class="btn btn-danger"
                       href="{% url "teachers:delete_teacher" teacher.pk %}">Delete</a></td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/teachers/teachers_create.html
{% extends "index/index.html" %}

{% block content %}
        <form enctype="multipart/form-data" action="{% url "teachers:create_teacher" %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
{% endblock content %}

src/templates/teachers/teachers_delete.html
{% extends "index/index.html" %}

{% block content %}
        <form method="post"> {% csrf_token %}
            <h1>Are you sure you want to delete this teacher?</h1>
            <div>
                <button type="submit" class="btn btn-danger">Submit</button>
            </div>
        </form>
{% endblock content %}

src/templates/teachers/teachers_update.html
{% extends "index/index.html" %}

{% block content %}
        <form method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
{% endblock content %}