src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import NotFoundView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls", namespace="students")),
    path("teachers/", include("teachers.urls", namespace="teachers")),
    path("groups/", include("groups.urls", namespace="groups")),
    path("oauth/", include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

src/core/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from core.views import IndexView, Login, Logout, Registration, ActivateUser, ProfileView

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="core"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>", ActivateUser.as_view(), name="activation"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

urlpatterns += staticfiles_urlpatterns()

src/groups/urls.py
from django.urls import path

from groups.views import GroupView, CreateGroupView, UpdateGroupView, DeleteGroupView, ShowGroupView

app_name = "groups"

urlpatterns = [
    path("", GroupView.as_view(), name="groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<uuid:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<uuid:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("<course>/", ShowGroupView.as_view(), name="show_group"),
]

src/students/urls.py
from django.urls import path

from students.views import StudentView, CreateStudentView, UpdateStudentView, DeleteStudentView, ShowStudentsView

app_name = "students"

urlpatterns = [
    path("", StudentView.as_view(), name="students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
    path("<group>/", ShowStudentsView.as_view(), name="show_students"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import TeacherView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", TeacherView.as_view(), name="teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:pk>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:pk>", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/templates/index/index.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Cover Template · Bootstrap v5.2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
</head>
<body class="d-flex h-100 text-center text-bg-dark"
      style="background-image: url('{% static "img/Background.jpg" %}'); background-position: center;
              background-repeat: no-repeat;
              background-size: cover;" ;>

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div style="display: flex; justify-content: space-between; align-items: center; ">
            <h3 class="float-md-start mb-0"><a style="color: white; text-decoration: none;"
                                               href="{% url "core:core" %}">LMS</a></h3>
            <img src={% static "img/Hillel_logo.png" %} height="50vh">
            <a href="#"
               class="nav-link fw-bold py-1 px-0 d-block link-dark text-decoration-none dropdown-toggle"
               data-bs-toggle="dropdown" aria-expanded="false">
                {% if user.is_authenticated %}
                    <img src="{{ user.photo.url }}" alt="mdo"
                         class="rounded-circle" width="32" height="32">
                {% else %}
                    <img src="{% static "img/White_flag_of_surrender.svg.png" %}" alt="mdo"
                         class="rounded-circle" width="32" height="32">
                {% endif %}
            </a>
            {% if user.is_authenticated %}
                <ul class="dropdown-menu text-small" style="">
                    <li><a class="dropdown-item" href="#">{{ user.username|title }}</a></li>
                    <li><a class="dropdown-item" href="{% url "core:profile" %}">Profile</a></li>
                    {% if user.is_staff %}
                        <li><a class="dropdown-item" href="{% url "admin:index" %}">Admin page</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url "core:logout" %}">Logout</a></li>
                </ul>
            {% else %}
                <ul class="dropdown-menu text-small" style="">
                    <li><a class="dropdown-item" href="{% url "core:login" %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url "core:registration" %}">Register</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Reset
                        password</a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item"
                           href="{% url "social:begin" "google-oauth2" %}">Gmail</a>
                    </li>
                    <li><a class="dropdown-item"
                           href="{% url "social:begin" "linkedin-oauth2" %}">Linkedin</a>
                    </li>
                    <li><a class="dropdown-item"
                           href="{% url "social:begin" "github" %}">Github</a>
                    </li>
                </ul>
            {% endif %}

        </div>
    </header>

    <main class="px-3">
        {% block content %}
            {% if user.is_authenticated %}
                <div>
                    <img src={% static "img/Python_logo.png" %} height="50vh">
                </div>
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "students:students" %}"
                           style="color: white">Students</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "teachers:teachers" %}" style="color: white">Teachers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "groups:groups" %}" style="color: white">Groups</a>
                    </li>
                </ul>
            {% else %}
                <a type="button" class="btn btn-secondary" href="{% url "core:login" %}"
                   style="color: white">Login</a>
            {% endif %}
        {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        <a style="margin: 10px; padding: 10px; color: white; text-decoration: none; font-size: calc(1.3rem + .6vw); font-weight: 500;
    line-height: 1.2;" href="starting_page1.html">Raise 404</a>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>

</body>
</html>