src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import NotFoundView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls", namespace="students")),
    path("teachers/", include("teachers.urls", namespace="teachers")),
    path("groups/", include("groups.urls", namespace="groups")),
    path("oauth/", include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

src/core/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from core.views import IndexView, Login, Logout, Registration, ActivateUser, ProfileView

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="core"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>", ActivateUser.as_view(), name="activation"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

urlpatterns += staticfiles_urlpatterns()

src/groups/urls.py
from django.urls import path

from groups.views import GroupView, CreateGroupView, UpdateGroupView, DeleteGroupView, ShowGroupView

app_name = "groups"

urlpatterns = [
    path("", GroupView.as_view(), name="groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<uuid:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<uuid:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("<course>/", ShowGroupView.as_view(), name="show_group"),
]

src/students/urls.py
from django.urls import path

from students.views import StudentView, CreateStudentView, UpdateStudentView, DeleteStudentView, ShowStudentsView

app_name = "students"

urlpatterns = [
    path("", StudentView.as_view(), name="students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
    path("<group>/", ShowStudentsView.as_view(), name="show_students"),
]

src/groups/models.py
from uuid import uuid4

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from faker import Faker


class Group(models.Model):
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid4,
        unique=True,
        db_index=True,
        editable=False,
    )
    course = models.CharField(
        max_length=100,
        blank=True,
        default="",
    )
    length_in_months = models.PositiveSmallIntegerField(
        null=True,
        validators=[MinValueValidator(1), MaxValueValidator(12)],
    )
    price = models.PositiveIntegerField(
        null=True,
        validators=[MinValueValidator(1000), MaxValueValidator(50000)],
    )
    number_of_students = models.PositiveSmallIntegerField(
        null=True,
        validators=[MinValueValidator(3), MaxValueValidator(30)],
    )
    lesson_duration = models.PositiveSmallIntegerField(
        null=True,
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )
    website = models.URLField(
        null=True,
    )

    def __str__(self):
        return f"{self.course}"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()

        for _ in range(count):
            cls.objects.create(
                course=cls.course,
                length_in_months=faker.random.randint(1, 12),
                price=faker.random.randint(1000, 50000),
                number_of_students=faker.random.randint(3, 30),
                lesson_duration=faker.random.randint(1, 5),
                website="https://" + faker.domain_name(),
            )

    class Meta:
        ordering = ("course", )

src/groups/forms.py
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, TemplateView

from groups.forms import GroupForm
from groups.models import Group


class GroupView(LoginRequiredMixin, TemplateView):
    model = Group
    template_name = "groups/groups.html"

    def get(self, request, *args, **kwargs):
        search_query = request.GET.get("q")
        if search_query:
            groups = Group.objects.filter(course__contains=search_query)
        else:
            groups = Group.objects.all()
        self.extra_context = {"groups": groups}

        return self.render_to_response(self.extra_context)


class CreateGroupView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/groups_create.html"
    success_url = reverse_lazy("groups:groups")


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/groups_update.html"
    success_url = reverse_lazy("groups:groups")


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy("groups:groups")
    template_name = "groups/groups_delete.html"


class ShowGroupView(LoginRequiredMixin, TemplateView):
    model = Group
    template_name = "groups/show_group.html"

    def get(self, request, *args, **kwargs):
        groups = Group.objects.filter(course=kwargs["course"])
        self.extra_context = {"groups": groups}

        return self.render_to_response(self.extra_context)

src/templates/groups/groups.html
{% extends "index/index.html" %}

{% block content %}
        <form action="{% url "groups:groups" %}" method="get">
            <input class="search" type="text" name="q" placeholder="Search" style="margin-bottom: 3vh">
        </form>
        <a style="width: 100%" type="button" class="btn btn-success" href="{% url "groups:create_group" %}">Create new group</a>
        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th scope="col">Course</th>
              <th scope="col">Length</th>
              <th scope="col">Price</th>
              <th scope="col">Number of students</th>
              <th scope="col">Lesson duration</th>
              <th scope="col">Website</th>
              <th scope="col">Students</th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
          {% for group in groups %}
            <tr>
              <td>{{ group.course }}</td>
              <td>{{ group.length_in_months }} months</td>
              <td>{{ group.price }} hryvnias</td>
              <td>{{ group.number_of_students }}</td>
              <td>{{ group.lesson_duration }} hours</td>
              <td><a href="{{ group.website }}">{{ group.website }}</a></td>
              <td><a type="button" class="btn btn-secondary" href="{% url "students:show_students" group.uuid %}">Students</a></td>
              <td><a type="button" class="btn btn-warning" href="{% url "groups:update_group" group.pk %}">Edit</a></td>
              <td><a type="button" class="btn btn-danger" href="{% url "groups:delete_group" group.pk %}">Delete</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
{% endblock content %}

src/templates/groups/groups_create.html
{% extends "index/index.html" %}

{% block content %}
        <form action="{% url "groups:create_group" %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
{% endblock content %}

src/templates/groups/groups_delete.html
{% extends "index/index.html" %}

{% block content %}
        <form method="post"> {% csrf_token %}
            <h1>Are you sure you want to delete this group?</h1>
            <div>
                <button type="submit" class="btn btn-danger">Submit</button>
            </div>
        </form>
{% endblock content %}

src/templates/groups/groups_update.html
{% extends "index/index.html" %}

{% block content %}
        <form method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
{% endblock content %}

src/templates/groups/show_group.html
{% extends "index/index.html" %}

{% block content %}
        <form action="{% url "groups:groups" %}" method="get">
            <input class="search" type="text" name="q" placeholder="Search" style="margin-bottom: 3vh">
        </form>
        <a style="width: 100%" type="button" class="btn btn-success" href="{% url "groups:create_group" %}">Create new group</a>
        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th scope="col">Course</th>
              <th scope="col">Length</th>
              <th scope="col">Price</th>
              <th scope="col">Number of students</th>
              <th scope="col">Lesson duration</th>
              <th scope="col">Website</th>
              <th scope="col">Students</th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
          {% for group in groups %}
            <tr>
              <td>{{ group.course }}</td>
              <td>{{ group.length_in_months }} months</td>
              <td>{{ group.price }} hryvnias</td>
              <td>{{ group.number_of_students }}</td>
              <td>{{ group.lesson_duration }} hours</td>
              <td><a href="{{ group.website }}">{{ group.website }}</a></td>
              <td><a type="button" class="btn btn-secondary" href="{% url "students:show_students" group.uuid %}">Students</a></td>
              <td><a type="button" class="btn btn-warning" href="{% url "groups:update_group" group.pk %}">Edit</a></td>
              <td><a type="button" class="btn btn-danger" href="{% url "groups:delete_group" group.pk %}">Delete</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
{% endblock content %}